#!/usr/bin/env bash
# ============================================================
# Ixora Observability — Grafana Foundation Validation
# Phase 8.1
#
# Validates that Grafana has started correctly and that all
# provisioned datasources are available with stable UIDs.
#
# Usage:
#   ./validate.sh
#   GRAFANA_URL=http://localhost:3000 ./validate.sh
#
# Prerequisites:
#   - Grafana is running: docker compose up -d grafana
#   - curl is installed on the host
#   - GF_ADMIN_USER and GF_ADMIN_PASSWORD are set (or defaults used)
#
# Exit codes:
#   0  All checks passed
#   1  One or more checks failed
# ============================================================

set -euo pipefail

GRAFANA_URL="${GRAFANA_URL:-http://localhost:3000}"
GRAFANA_USER="${GF_ADMIN_USER:-admin}"
GRAFANA_PASS="${GF_ADMIN_PASSWORD:-}"
PASS_COUNT=0
FAIL_COUNT=0

# ── helpers ──────────────────────────────────────────────────

green()  { printf "\033[0;32m✓ %s\033[0m\n" "$*"; }
red()    { printf "\033[0;31m✗ %s\033[0m\n" "$*"; }
yellow() { printf "\033[0;33m  %s\033[0m\n" "$*"; }

pass() { green "$1";  (( PASS_COUNT++ )) || true; }
fail() { red   "$1";  (( FAIL_COUNT++ )) || true; }

grafana_get() {
  local path="$1"
  curl --silent --fail \
    --user "${GRAFANA_USER}:${GRAFANA_PASS}" \
    "${GRAFANA_URL}${path}"
}

# ── check: admin password set ─────────────────────────────────

if [[ -z "${GRAFANA_PASS}" ]]; then
  fail "GF_ADMIN_PASSWORD is not set — cannot authenticate"
  echo ""
  echo "  Set it in .env and source it, or run:"
  echo "    GF_ADMIN_PASSWORD=<pass> ./validate.sh"
  exit 1
fi

echo ""
echo "Grafana Foundation Validation — Phase 8.1"
echo "Target: ${GRAFANA_URL}"
echo "────────────────────────────────────────────────"
echo ""

# ── 1. Health check ───────────────────────────────────────────

echo "1. Grafana health"
if grafana_get "/api/health" 2>/dev/null | grep -q '"database": "ok"'; then
  pass "Grafana is healthy (database: ok)"
else
  fail "Grafana health check failed — is the container running?"
  yellow "  docker compose up -d grafana"
  echo ""
  echo "────────────────────────────────────────────────"
  echo "FAIL: ${FAIL_COUNT} check(s) failed, ${PASS_COUNT} passed."
  exit 1
fi

# ── 2. Datasource UIDs ────────────────────────────────────────

echo ""
echo "2. Datasource UIDs (must be stable — never autogenerated)"

check_datasource() {
  local label="$1"
  local expected_uid="$2"
  local ds_json
  ds_json=$(grafana_get "/api/datasources/uid/${expected_uid}" 2>/dev/null || echo "")
  if echo "${ds_json}" | grep -q "\"uid\":\"${expected_uid}\""; then
    pass "${label} datasource: uid=${expected_uid}"
  else
    fail "${label} datasource uid '${expected_uid}' not found"
    yellow "  Check grafana/provisioning/datasources/datasources.yaml"
  fi
}

check_datasource "Prometheus" "ixora-prometheus"
check_datasource "Loki"       "ixora-loki"
check_datasource "Tempo"      "ixora-tempo"

# ── 3. Default datasource ─────────────────────────────────────

echo ""
echo "3. Default datasource"
DEFAULT_DS=$(grafana_get "/api/datasources" 2>/dev/null | \
  python3 -c "import sys,json; ds=[d for d in json.load(sys.stdin) if d.get('isDefault')]; print(ds[0]['uid'] if ds else 'none')" 2>/dev/null || echo "none")

if [[ "${DEFAULT_DS}" == "ixora-prometheus" ]]; then
  pass "Default datasource: ixora-prometheus (Prometheus)"
else
  fail "Default datasource is '${DEFAULT_DS}', expected 'ixora-prometheus'"
fi

# ── 4. Datasource connectivity ────────────────────────────────

echo ""
echo "4. Datasource connectivity (proxy health)"

check_ds_health() {
  local label="$1"
  local uid="$2"
  # Use curl without --fail so we get the body even for 4xx responses.
  # Some plugins (e.g. Tempo) return 404 "notImplemented" — treat as pass.
  local raw
  raw=$(curl --silent \
    --user "${GRAFANA_USER}:${GRAFANA_PASS}" \
    "${GRAFANA_URL}/api/datasources/uid/${uid}/health" 2>/dev/null || echo '{"status":"error"}')
  local result
  result=$(echo "${raw}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status','unknown'))" 2>/dev/null || echo "error")
  if [[ "${result}" == "OK" ]]; then
    pass "${label} connectivity: OK"
  elif echo "${raw}" | grep -qi "notImplemented\|not implemented"; then
    # Tempo plugin does not implement the /health endpoint in Grafana 11.
    # The datasource was provisioned correctly; backend connectivity is
    # verified separately by Grafana when the datasource is saved.
    pass "${label} connectivity: health endpoint not supported by plugin (datasource provisioned)"
  else
    fail "${label} connectivity: ${result} — is the backend running?"
    yellow "  docker compose up -d prometheus loki tempo"
  fi
}

check_ds_health "Prometheus" "ixora-prometheus"
check_ds_health "Loki"       "ixora-loki"
check_ds_health "Tempo"      "ixora-tempo"

# ── 5. Provisioning is idempotent ─────────────────────────────

echo ""
echo "5. Provisioning locked (editable: false)"

check_ds_readonly() {
  local label="$1"
  local uid="$2"
  local readonly_val
  readonly_val=$(grafana_get "/api/datasources/uid/${uid}" 2>/dev/null | \
    python3 -c "import sys,json; d=json.load(sys.stdin); print(str(d.get('readOnly', False)).lower())" 2>/dev/null || echo "false")
  if [[ "${readonly_val}" == "true" ]]; then
    pass "${label}: readOnly=true (changes require provisioning file update)"
  else
    fail "${label}: readOnly=false — datasource may be edited via UI (check editable: false in YAML)"
  fi
}

check_ds_readonly "Prometheus" "ixora-prometheus"
check_ds_readonly "Loki"       "ixora-loki"
check_ds_readonly "Tempo"      "ixora-tempo"

# ── 6. No manual datasources ──────────────────────────────────

echo ""
echo "6. No unprovisioned datasources"
DS_COUNT=$(grafana_get "/api/datasources" 2>/dev/null | \
  python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

if [[ "${DS_COUNT}" -eq 3 ]]; then
  pass "Datasource count: 3 (Prometheus + Loki + Tempo — no extras)"
else
  fail "Datasource count: ${DS_COUNT} (expected 3) — unprovisioned datasources present?"
  yellow "  Remove manually-created datasources from the Grafana UI"
fi

# ── Summary ───────────────────────────────────────────────────

echo ""
echo "────────────────────────────────────────────────"
if [[ "${FAIL_COUNT}" -eq 0 ]]; then
  green "PASS: All ${PASS_COUNT} checks passed. Grafana foundation is ready."
  echo ""
else
  red "FAIL: ${FAIL_COUNT} check(s) failed, ${PASS_COUNT} passed."
  echo ""
  exit 1
fi
